name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  # Job to validate code and run tests
  validate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install project dependencies
        run: |
          pip install fastapi uvicorn psycopg2-binary azure-identity azure-storage-blob

      - name: Run linting and static analysis
        run: |
          echo "Running static analysis..."
          flake8 --max-line-length=120 . || echo "Linting issues found"

      - name: Execute unit tests
        run: |
          echo "Running tests..."
          pytest --disable-warnings tests/

  # Job to build and push Docker image
  build_and_push:
    needs: validate_code
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image..."
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
