name: Run Tests

# On exécute le code lors d'un pull request sur la branche principale:

on:
  push:
    branches:
      - main

# ce qu'on doit faire lors d'un pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
     
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version-file: '.python-version'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv 

    - name: Run tests
      run: uv run tests/test_root.py
